name: Generate and Upload Root Zone

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Generate root zone file
      run: |
        TODAY=$(date +%Y-%m-%d)
        dig @b.root-servers.net . AXFR > ${TODAY}_root.zone

    - name: Upload root zone file
      uses: actions/upload-artifact@v3
      with:
        name: root-zone
        path: ./*_root.zone
